# Generated by Django 5.1.7 on 2025-09-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100, verbose_name='属性名')),
                ('value', models.TextField(verbose_name='属性值')),
                ('source_text', models.TextField(blank=True, null=True, verbose_name='原文来源')),
                ('embedding_vector', models.BinaryField(blank=True, null=True, verbose_name='向量表示')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='products.product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '商品知识',
                'verbose_name_plural': '商品知识库',
                'db_table': 'product_knowledge',
            },
        ),
    ]
