# Generated by Django 5.1.7 on 2025-09-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='用户ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('action_type', models.CharField(default='view', max_length=20, verbose_name='行为类型')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='浏览商品')),
            ],
            options={
                'verbose_name': '用户行为日志',
                'verbose_name_plural': '用户行为日志',
                'db_table': 'user_behavior',
                'indexes': [models.Index(fields=['user_id', '-viewed_at'], name='user_behavi_user_id_531bb7_idx')],
            },
        ),
    ]
