# Generated by Django 5.1.7 on 2025-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='用户ID')),
                ('preferred_categories', models.JSONField(default=list, verbose_name='偏好类别')),
                ('price_preference', models.CharField(blank=True, max_length=50, null=True, verbose_name='价格区间偏好')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='画像更新时间')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像库',
                'db_table': 'user_profile',
            },
        ),
    ]
