# Generated by Django 5.1.7 on 2025-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='商品ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('category', models.CharField(max_length=100, verbose_name='商品类别')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('specifications', models.JSONField(default=dict, verbose_name='规格参数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
                'db_table': 'product',
            },
        ),
    ]
